[theme]
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#334155"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true

[browser]
gatherUsageStats = false
